export const sidebarData = [
  {
    id: "N001",
    name: "Accueil",
    icon: "fa-solid fa-house",
    path: "/youtube-clone",
  },
  {
    id: "N002",
    name: "Explorer",
    icon: "fa-regular fa-compass",
    path: "/explorer",
  },
  {
    id: "N003",
    name: "Abonnements",
    icon: "fa-brands fa-square-youtube",
    path: "/subscriptions",
  },
  {
    id: "N004",
    name: "Favoris",
    icon: "fa-solid fa-thumbs-up",
    path: "/favorites",
  },
  {
    id: "N005",
    name: "En direct",
    icon: "fa-solid fa-eye",
    path: "/live",
  },
  {
    id: "N006",
    name: "À regarder",
    icon: "fa-regular fa-clock",
    path: "/watchlater",
  },
  {
    id: "N007",
    name: "Gaming",
    icon: "fa-solid fa-gamepad",
    path: "/gaming",
  },
  {
    id: "N008",
    name: "Film",
    icon: "fa-solid fa-film",
    path: "/film",
  },
  {
    id: "N009",
    name: "Voir plus",
    icon: "fa-solid fa-angle-down",
  },
  {
    id: "N010",
    name: "Voir moins",
    icon: "fa-solid fa-angle-up",
  },
  {
    id: "N011",
    name: "Musique",
    icon: "fa-solid fa-music",
    path: "/music",
  },
  {
    id: "N012",
    name: "Western",
    icon: "fa-solid fa-hat-cowboy-side",
    path: "/western",
  },
  {
    id: "N013",
    name: "Paramètres",
    icon: "fa-solid fa-gears",
    path: "/settings",
  },
  {
    id: "N014",
    name: "Aide",
    icon: "fa-regular fa-circle-question",
    path: "/help",
  },
  {
    id: "N015",
    name: "Signalement",
    icon: "fa-solid fa-triangle-exclamation",
    path: "/report",
  },
];
