export const tagsData = [
  { name: "Tous" },
  { name: "Frontend" },
  { name: "Musique" },
  { name: "Arte" },
  { name: "React" },
  { name: "Backend" },
  { name: "Vue" },
  { name: "Gaming" },
  { name: "Humour" },
  { name: "Fullstack" },
  { name: "Firebase" },
  { name: "Unity" },
  { name: "Frontend" },
  { name: "Vue" },
  { name: "Gaming" },
  { name: "Humour" },
  { name: "Fullstack" },
  { name: "Unity" },
  { name: "Web" },
];
